# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    paths-ignore:
      - 'README.md'
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with: 
        fetch-depth: 0

    - name: Get Previous tag
      id: previoustag
      uses: 'WyriHaximus/github-action-get-previous-tag@v1'
      env:
        GITHUB_TOKEN: ${{ secrets.APPVEYOR_SECRET }}
          
    - name: Process Previous Tag
      id: processtag
      run: |
        PREVIOUS_TAG="${{ steps.previoustag.outputs.tag }}"  # Example: "v1.100.0"
        NUMERIC_PART=$(echo "$PREVIOUS_TAG" | cut -d '.' -f2)  # Gets "100"
        INCREMENTED=$((NUMERIC_PART + 1))  # 100 -> 101
        echo "NEW_TAG=v2.${INCREMENTED}.0" >> $GITHUB_ENV
        echo "${{ env.NEW_TAG }}" > ./src/version
      shell: bash

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Publish build artifacts
      run: dotnet publish --configuration Release --output ./output
      
    - name: Zip the output folder
      run: | 
        Compress-Archive -Path ./output/* -DestinationPath ./NintendAUX.zip
        
    - name: Create release
      uses: ncipollo/release-action@v1.14.0
      with:
        name: ${{ env.NEW_TAG }}
        tag: ${{ env.NEW_TAG }}
        token: ${{ secrets.APPVEYOR_SECRET }}
        artifacts: ./NintendAUX.zip 
        body: |
          NintendAUX **requires** the [.NET Runtime 9.0](https://dotnet.microsoft.com/en-us/download/dotnet/9.0) minimum to work! 

          This was built automatically by the repository!
          Current commit: `${{ github.event.head_commit.message }}`
